### ISSUE TITLE
fails with .Xauthority does not exist

### ISSUE THREAD

**Issue by aurelijusrozenas** [awamper/draobpilc#13]
Hi,

in new Ubuntu 17.10 installation  I get exception that `/home/user/.Xauthority` does not exist and draobpilc does not start. I did not have this file in previous installation, but draobpilc was working. Any ideas? What am I doing wrong?

Thanks.

**Comment by awamper** [comment]
Wayland? Try login with X it should create .Xauthority.

**Comment by aurelijusrozenas** [comment]
Yes, under Xorg it works.
Just out of curiosity, any chance running this in Wayland?

**Comment by awamper** [comment]
It should run in Wayland but there were some errors with shortcuts.
