### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by najamelan** [awamper/draobpilc#2]
I am on debian but I can't get it to work properly:

I have the following packages installed.

gir1.2-gpaste-4.0/testing,unstable,now 3.18.2-1 amd64 [installed]
gpaste/testing,unstable,now 3.18.2-1 amd64 [installed,auto-removable]
libgpaste4/testing,unstable,now 3.18.2-1 amd64 [installed]

When I run draobpilc I get:
/usr/local/lib/python3.4/dist-packages/draobpilc/lib/utils.py:23: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Job 2, “draobpilc &” has ended

It seems that the app stops running immediately. When I press Ctrl+Alt+C I get the gtk interface of gpaste, rather than the gnome shell interface as shown in the screenshot...

**Comment by awamper** [comment]
This warning is harmless and i don't know why the app stops immediately without any errors.

**Comment by awamper** [comment]
Does it show any notifications? Try to start it without "&" at the end.

**Comment by najamelan** [comment]
In the mean time I have rebooted and it does show a notification that it's running and to press Ctrl-Alt-C. When I do, now the gtk interface of gpaste does no longer pop up, but neither does the interface from draobpilc. I get this error in my logs when I press Ctrl-Alt-C:

Jan 16 10:59:30 computer gnome-session[2731]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2200008 (Draobpilc)

The application I'm in does seem to loose focus at this moment.

**Comment by awamper** [comment]
This warning is also harmless. Run the app in the terminal and see if there any errors when you are pressing Ctrl-Alt-C.

**Comment by najamelan** [comment]
Nothing else appears, but there is no GUI...

**Comment by awamper** [comment]
Try update it.

**Comment by najamelan** [comment]
Thanks alot! It seems to be working. I have to go now, so can't test further right now, but I'll sure be using it alot.
