### ISSUE TITLE
draobpilc does not work with new version of gpaste 3.38

### ISSUE THREAD

**Issue by bsiara** [awamper/draobpilc#26]
Yesterday I upgrade my debian testing to new version and also gpaste was updated to version 3.38:
`dpkg -l | grep gpaste`
![image](https://user-images.githubusercontent.com/24296719/100734806-84d99c00-33d0-11eb-89c5-4772bfba4003.png)
after update draobplic stop working because can not detect gpaste version:
![image](https://user-images.githubusercontent.com/24296719/100734692-578cee00-33d0-11eb-8d83-057ac9abbb2f.png)

**Comment by JRJurman** [comment]
Is this issue confirmed to be resolved? I just updated my OS to POP!_OS 20.10, and also noticed this issue (certainly other packages may have been bumped as well).
```
/home/jrjurman/.local/lib/python3.8/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
GPaste version >= 3.18 is required, current version == Not detected.
```

I have a similar list of packages installed, and gpaste does work on the machine
```
02:26 $ dpkg -l | grep gpaste
ii  gir1.2-gpaste-1.0                                3.38.2-1                                                  amd64        GObject introspection data for the libgpaste13 library
ii  gpaste                                           3.38.2-1                                                  amd64        Clipboard management system for GNOME
ii  libgpaste13                                      3.38.2-1                                                  amd64        Clipboard management system for GNOME - library
```

**Comment by bsiara** [comment]
Hi,
Unfournaterly problem still exist on debian testing, I installed latest
version and still get error:
[image: obraz.png]


śr., 7 kwi 2021 o 08:31 Jesse Jurman ***@***.***> napisał(a):

**Comment by awamper** [comment]
Have you tried gpaste338 branch?

**Comment by bsiara** [comment]
The same error
[image: obraz.png]


pon., 12 kwi 2021 o 08:50 Ivan ***@***.***> napisał(a):

**Comment by JRJurman** [comment]
After switching branches and doing a `pip3 install .` this is the new error I get:
```
✔ ~/Apps/draobpilc [gpaste338|✔] 
12:33 $ draobpilc
/home/jrjurman/.local/lib/python3.8/site-packages/draobpilc/main.py:27: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import Gtk
/home/jrjurman/.local/lib/python3.8/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/home/jrjurman/.local/lib/python3.8/site-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste
```

![image](https://user-images.githubusercontent.com/326557/115153158-9dc2b100-a042-11eb-86a3-ae5a8c55c69b.png)

**Comment by Phidica** [comment]
@JRJurman I don't think those are serious errors. I see the same ones printed, but draobpilc launches just fine for me afterwards. I think with this branch the problem should be solved
