### ISSUE TITLE
Not properly working.

### ISSUE THREAD

**Issue by Abhinav1217** [awamper/draobpilc#3]
I have updated GPaste and python. Then reinstall this. Still I am getting this issue.

```
[Abhinav@abhinav-f23 ~] $ draobpilc 
/usr/lib/python3.4/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python3.4/site-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste
^[^H^[^H^[^B^[^H
```

I do get a notification `Draophilic is loaded press ctrl + alt + H ` but it is not working. Notice the last line. `^[^H` that is me pressing the `ctrl+alt+H` When I minimize terminal then keys are send to whatever app is open. So it is unusable.

On unrelated note, What is the main reason you abandon a perfectly working shell plugin and made this.

**Comment by awamper** [comment]
This is GPaste bug, try to change hotkeys.

> On unrelated note, What is the main reason you abandon a perfectly working shell plugin and made this.

Because i wanted to abandon a perfectly working shell plugin and make this.
