### ISSUE TITLE
Fedora 24 support

### ISSUE THREAD

**Issue by nicky14** [awamper/draobpilc#4]
Hi, i'm on F24 but, after system update, the application will crash with error:

$ draobpilc 

/usr/lib/python2.7/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste
Traceback (most recent call last):
  File "/usr/bin/draobpilc", line 9, in <module>
    load_entry_point('Draobpilc==0.1', 'gui_scripts', 'draobpilc')()
  File "/usr/lib/python2.7/site-packages/draobpilc/main.py", line 177, in run
    app = Application()
  File "/usr/lib/python2.7/site-packages/draobpilc/application.py", line 50, in __init__
    super().__init__()
TypeError: super() takes at least 1 argument (0 given)

**Comment by awamper** [comment]
Did you install it with pip or pip3?

**Comment by awamper** [comment]
Try reinstall it.

**Comment by nicky14** [comment]
In F24 there's only pip.
I've install it with:

`pip3 install git+https://....`

and I've try to reinstall it but same error

**Comment by nicky14** [comment]
Also the command:
`draobpilc --install-desktop-file`
produce a similar error:
`/usr/lib/python2.7/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/usr/lib/python2.7/site-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste
Traceback (most recent call last):
  File "/usr/bin/draobpilc", line 9, in <module>
    load_entry_point('Draobpilc==0.1', 'gui_scripts', 'draobpilc')()
  File "/usr/lib/python2.7/site-packages/draobpilc/main.py", line 170, in run
    install_desktop_file()
  File "/usr/lib/python2.7/site-packages/draobpilc/main.py", line 95, in install_desktop_file
    with open(desktop_tpl, encoding='utf-8') as tpl_file:
TypeError: 'encoding' is an invalid keyword argument for this function`

**Comment by nicky14** [comment]
By upgrading F23 to F24, pip3 was not available. Now it work, sorry and thanks for all!
