### ISSUE TITLE
Could not be startet

### ISSUE THREAD

**Issue by meistadieb** [awamper/draobpilc#5]
I am running Ubuntu with gnome, 16.04.1

I downloaded the zip and installed with the command: pip3 install <path to draobpilc root dir> Worked very well, but no icon was shown. Reload of the gnome shell with alt+f2 r was not helpful. So I tried to start it directly from a console and got a tracepack:

python3 draobpilc
/home/user.local/lib/python3.5/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 890, in _find_spec
AttributeError: 'DynamicImporter' object has no attribute 'find_spec'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "draobpilc", line 11, in <module>
    sys.exit(run())
  File "/home/user/.local/lib/python3.5/site-packages/draobpilc/main.py", line 145, in run
    from draobpilc.application import Application
  File "/home/user/.local/lib/python3.5/site-packages/draobpilc/application.py", line 47, in <module>
    from draobpilc.widgets.preferences import show_preferences
  File "/home/user/.local/lib/python3.5/site-packages/draobpilc/widgets/preferences.py", line 24, in <module>
    from gi.repository import GPaste
  File "/usr/lib/python3/dist-packages/gi/importer.py", line 127, in find_module
    'introspection typelib not found' % namespace)
ImportError: cannot import name GPaste, introspection typelib not found

**Comment by awamper** [comment]
Do you have gpaste and gir1.2-gpaste-4.0 installed?

**Comment by meistadieb** [comment]
Thank you for your fast reply.

gir1.2-gpaste-4.0 was not installed. After installation, draobpilc could be started.

If I start it from console, I still get some errors:
python3 draobpilc
/home/user/.local/lib/python3.5/site-packages/draobpilc/lib/utils.py:25: PyGIWarning: Notify was imported without specifying a version first. Use gi.require_version('Notify', '0.7') before import to ensure that the right version gets loaded.
  from gi.repository import Notify
/home/user/.local/lib/python3.5/site-packages/draobpilc/widgets/preferences.py:24: PyGIWarning: GPaste was imported without specifying a version first. Use gi.require_version('GPaste', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GPaste

(draobpilc:8289): Gtk-WARNING **: Theme directory  of theme oxygen has no size field

I'm missing a task bar icon, like the gnome shell extension had. Is there only the possibility to open draobpilc with the keyboard shortcut?

**Comment by awamper** [comment]
> I'm missing a task bar icon, like the gnome shell extension had. Is there only the possibility to open draobpilc with the keyboard shortcut?

Keyboard shortcut and desktop file. Lets discuss this in #6.

**Comment by awamper** [comment]
Also these errors are harmless.
