### ISSUE TITLE
Use draopilc in combination with shell extension Keyman

### ISSUE THREAD

**Issue by meistadieb** [awamper/draobpilc#7]
I'm using the Gnome shell extension Keyman which makes it possible to easily copy passwords from Seafile to the clipboard. The passwords are shown in draobilc history (ctrl+alt+h). Keyman will keep the passwords only for a configured time in the clipboard, but after that, they are still in the draobpilc history. With the old Shell Extension this was no problem, the passwords vanished after the configured time from the clipboard. Is there the possibility to reconfigure this?

**Comment by awamper** [comment]
Draobpilc just represents gpaste history, see gpaste-client history in terminal if the password is there then it either gpaste or keyman bug.

**Comment by meistadieb** [comment]
Yes, you are correct. It stays in the gpaste-client history.
